title: "bors-ng"
description: "A merge bot for GitHub pull requests"
url: "https://bors.tech"

permalink: pretty
paginate: 10

kramdown:
  input: GFM
  hard_wrap: false

gems:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-redirect-from
